---
- name: distribute controller certs
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/workstation/files/ca.pem
    - roles/workstation/files/ca-key.pem
    - roles/controller/files/kubernetes.pem
    - roles/controller/files/kubernetes-key.pem
  become: true
