---
- name: distribute encryption-config.yaml file to controllers
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/workstation/templates/encryption-config.yaml
  become: true
