kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: "c5uhGEWLwsStZgyNiXnAfG61vAz24k/3hJF9texfQ3I="
      - identity: {}
