kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: "yO4uTG3Uq+BUw3ngmLyOUx/1gg4fe8KAuOZpjHjiJfw="
      - identity: {}
