---
- name: create SSL certs, kubeconfig files, and configure kubectl locally
  hosts: localhost
  roles:
    - workstation

- name: configure controller nodes
  hosts: tag_controller
  roles:
    - controller

- name: configure worker nodes
  hosts: tag_worker
  roles:
    - worker
