---
- name: create SSL certs and kubeconfig files
  hosts: localhost
  roles:
    - workstation

- name: configure controller nodes
  hosts: tag_controller
  roles:
    - controller

- name: configure worker nodes
  hosts: tag_worker
  roles:
    - worker
