---
- name: distribute worker certs
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/common/templates/ca.pem
    - roles/worker/templates/{{ ansible_hostname }}.pem
    - roles/worker/templates/{{ ansible_hostname }}-key.pem
  become: true
