---
- name: distribute files to worker nodes
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/worker/files/kube-proxy.kubeconfig
    - roles/worker/files/{{ ansible_hostname }}.kubeconfig
  become: true
