---
- name: Check whether worker components are already installed
  stat:
    path: /etc/systemd/system/kubelet.service
  register: worker_installed

- name: install worker components
  script: roles/worker/files/worker.sh
  when: worker_installed.stat.exists == False
